/*
 * Apply Vault runtime configuration.
 *
 * One-time setup:
 * 1) Deploy google-apps-script.gs as a Google Apps Script Web App.
 * 2) Paste the /exec URL into apiUrl below.
 *
 * After that, DO NOT edit this file to add/remove people.
 * Manage email + password + status directly in the Google Sheet tab: Vault Access.
 */
window.MEHRSHAD_ACCESS = {
  ownerEmail: 'mehrsh3d@gmail.com',
  apiUrl: 'https://script.google.com/macros/s/AKfycbwpcJ4GUEbty_N_9iFEiU_WDr39YtjDUiSzdFHVDKne6ieew3OXkQGh3f8JrcrJj6TT/exec',
  privateJourneyUrl: 'apply-vault-private.html',
  gateUrl: 'apply-vault.html'
};
